version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      astro-and-cloudflare:
        patterns: ["astro", "@astrojs/*", "wrangler", "@cloudflare/*"]
      lint-and-format:
        patterns:
          [
            "eslint",
            "@eslint/*",
            "typescript-eslint",
            "eslint-plugin-*",
            "prettier",
            "prettier-plugin-*",
            "globals",
          ]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
